FROM hopsoft/graphite-statsd:latest

ADD storage-schemas.conf /opt/graphite/conf/storage-schemas.conf
ADD carbon.conf /opt/graphite/conf/carbon.conf
ADD local_settings.py /opt/graphite/webapp/graphite/local_settings.py
